// Mocks generated by Mockito 5.4.6 from annotations
// in jet_customer/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:ui' as _i31;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter/material.dart' as _i29;
import 'package:flutter_architecture_blueprint/core/error/failures.dart' as _i18;
import 'package:flutter_architecture_blueprint/core/network/dio_client.dart' as _i13;
import 'package:flutter_architecture_blueprint/core/network/network_info.dart' as _i15;
import 'package:flutter_architecture_blueprint/core/services/secure_storage_service.dart' as _i16;
import 'package:flutter_architecture_blueprint/features/address/data/datasources/address_local_data_source.dart'
    as _i24;
import 'package:flutter_architecture_blueprint/features/address/data/models/address_model.dart'
    as _i25;
import 'package:flutter_architecture_blueprint/features/address/domain/entities/address.dart'
    as _i36;
import 'package:flutter_architecture_blueprint/features/address/domain/repositories/address_repository.dart'
    as _i8;
import 'package:flutter_architecture_blueprint/features/address/domain/usecases/get_addresses.dart'
    as _i58;
import 'package:flutter_architecture_blueprint/features/address/domain/usecases/get_selected_address.dart'
    as _i59;
import 'package:flutter_architecture_blueprint/features/address/domain/usecases/select_address.dart'
    as _i60;
import 'package:flutter_architecture_blueprint/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i17;
import 'package:flutter_architecture_blueprint/features/auth/data/models/auth_tokens_model.dart'
    as _i19;
import 'package:flutter_architecture_blueprint/features/auth/domain/entities/auth_session.dart'
    as _i33;
import 'package:flutter_architecture_blueprint/features/auth/domain/entities/auth_tokens.dart'
    as _i32;
import 'package:flutter_architecture_blueprint/features/auth/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:flutter_architecture_blueprint/features/auth/domain/usecases/check_auth_status.dart'
    as _i52;
import 'package:flutter_architecture_blueprint/features/auth/domain/usecases/get_app_bootstrap.dart'
    as _i51;
import 'package:flutter_architecture_blueprint/features/auth/domain/usecases/request_otp.dart'
    as _i49;
import 'package:flutter_architecture_blueprint/features/auth/domain/usecases/sign_out.dart'
    as _i53;
import 'package:flutter_architecture_blueprint/features/auth/domain/usecases/verify_otp.dart'
    as _i50;
import 'package:flutter_architecture_blueprint/features/cart/domain/entities/cart_item.dart'
    as _i38;
import 'package:flutter_architecture_blueprint/features/cart/domain/repositories/cart_repository.dart'
    as _i37;
import 'package:flutter_architecture_blueprint/features/home/data/datasources/home_remote_data_source.dart'
    as _i20;
import 'package:flutter_architecture_blueprint/features/home/data/models/home_bootstrap_model.dart'
    as _i21;
import 'package:flutter_architecture_blueprint/features/auth/domain/entities/app_bootstrap.dart'
    as _i5;
import 'package:flutter_architecture_blueprint/features/home/domain/entities/home_bootstrap.dart'
    as _i66;
import 'package:flutter_architecture_blueprint/features/home/domain/repositories/home_repository.dart'
    as _i34;
import 'package:flutter_architecture_blueprint/features/home/domain/usecases/get_home_bootstrap.dart'
    as _i48;
import 'package:flutter_architecture_blueprint/features/item/domain/entities/item.dart' as _i39;
import 'package:flutter_architecture_blueprint/features/item/domain/repositories/item_repository.dart'
    as _i10;
import 'package:flutter_architecture_blueprint/features/item/domain/usecases/get_items_by_supplier_id.dart'
    as _i62;
import 'package:flutter_architecture_blueprint/features/notifications/data/datasources/notification_local_data_source.dart'
    as _i22;
import 'package:flutter_architecture_blueprint/features/notifications/data/models/notification_model.dart'
    as _i23;
import 'package:flutter_architecture_blueprint/features/notifications/domain/entities/notification.dart'
    as _i35;
import 'package:flutter_architecture_blueprint/features/notifications/domain/repositories/notification_repository.dart'
    as _i7;
import 'package:flutter_architecture_blueprint/features/notifications/domain/usecases/get_notifications.dart'
    as _i54;
import 'package:flutter_architecture_blueprint/features/notifications/domain/usecases/get_unread_count.dart'
    as _i55;
import 'package:flutter_architecture_blueprint/features/notifications/domain/usecases/mark_all_as_read.dart'
    as _i57;
import 'package:flutter_architecture_blueprint/features/notifications/domain/usecases/mark_as_read.dart'
    as _i56;
import 'package:flutter_architecture_blueprint/features/orders/domain/entities/order.dart'
    as _i41;
import 'package:flutter_architecture_blueprint/features/orders/domain/repositories/order_repository.dart'
    as _i40;
import 'package:flutter_architecture_blueprint/features/profile/data/datasources/user_remote_datasource.dart'
    as _i26;
import 'package:flutter_architecture_blueprint/features/profile/data/models/user_model.dart'
    as _i4;
import 'package:flutter_architecture_blueprint/features/profile/domain/entities/user.dart'
    as _i27;
import 'package:flutter_architecture_blueprint/features/profile/domain/repositories/user_repository.dart'
    as _i9;
import 'package:flutter_architecture_blueprint/features/profile/domain/usecases/update_user.dart'
    as _i61;
import 'package:flutter_architecture_blueprint/features/search/domain/entities/search_item.dart'
    as _i42;
import 'package:flutter_architecture_blueprint/features/search/domain/entities/search_supplier.dart'
    as _i43;
import 'package:flutter_architecture_blueprint/features/search/domain/repositories/search_repository.dart'
    as _i11;
import 'package:flutter_architecture_blueprint/features/search/domain/usecases/search_items.dart'
    as _i63;
import 'package:flutter_architecture_blueprint/features/search/domain/usecases/search_suppliers.dart'
    as _i64;
import 'package:flutter_architecture_blueprint/features/supplier/domain/entities/supplier.dart'
    as _i44;
import 'package:flutter_architecture_blueprint/features/supplier/domain/entities/supplier_business_type.dart'
    as _i45;
import 'package:flutter_architecture_blueprint/features/supplier/domain/repositories/supplier_repository.dart'
    as _i12;
import 'package:flutter_architecture_blueprint/features/supplier/domain/usecases/get_suppliers_by_business_type.dart'
    as _i65;
import 'package:flutter_architecture_blueprint/shared/localization/data/datasources/locale_local_data_source.dart'
    as _i30;
import 'package:flutter_architecture_blueprint/shared/localization/domain/repositories/locale_repository.dart'
    as _i47;
import 'package:flutter_architecture_blueprint/shared/theme/data/datasources/theme_mode_local_data_source.dart'
    as _i28;
import 'package:flutter_architecture_blueprint/shared/theme/domain/repositories/theme_mode_repository.dart'
    as _i46;
import 'package:flutter_architecture_blueprint/core/usecases/usecase.dart' as _i67;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_3 extends _i1.SmartFake implements _i4.UserModel {
  _FakeUserModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnit_4 extends _i1.SmartFake implements _i3.Unit {
  _FakeUnit_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeBootstrap_5 extends _i1.SmartFake implements _i5.AppBootstrap {
  _FakeHomeBootstrap_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_6 extends _i1.SmartFake
    implements _i6.AuthRepository {
  _FakeAuthRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationRepository_7 extends _i1.SmartFake
    implements _i7.NotificationRepository {
  _FakeNotificationRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressRepository_8 extends _i1.SmartFake
    implements _i8.AddressRepository {
  _FakeAddressRepository_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRepository_9 extends _i1.SmartFake
    implements _i9.UserRepository {
  _FakeUserRepository_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeItemRepository_10 extends _i1.SmartFake
    implements _i10.ItemRepository {
  _FakeItemRepository_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchRepository_11 extends _i1.SmartFake
    implements _i11.SearchRepository {
  _FakeSearchRepository_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupplierRepository_12 extends _i1.SmartFake
    implements _i12.SupplierRepository {
  _FakeSupplierRepository_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i13.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i14.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #options: options},
            ),
            returnValue: _i14.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters, #options: options},
                ),
              ),
            ),
          )
          as _i14.Future<_i2.Response<dynamic>>);

  @override
  _i14.Future<_i2.Response<dynamic>> post(
    String? path, {
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path], {#data: data, #options: options}),
            returnValue: _i14.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #options: options},
                ),
              ),
            ),
          )
          as _i14.Future<_i2.Response<dynamic>>);

  @override
  _i14.Future<_i2.Response<dynamic>> put(
    String? path, {
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#data: data, #options: options}),
            returnValue: _i14.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {#data: data, #options: options},
                ),
              ),
            ),
          )
          as _i14.Future<_i2.Response<dynamic>>);

  @override
  _i14.Future<_i2.Response<dynamic>> delete(
    String? path, {
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#data: data, #options: options},
            ),
            returnValue: _i14.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#data: data, #options: options},
                ),
              ),
            ),
          )
          as _i14.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i15.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i16.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i14.Future<String?>.value(),
          )
          as _i14.Future<String?>);

  @override
  _i14.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> deleteAllTokens() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllTokens, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i17.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> requestOtp(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [phoneNumber]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#requestOtp, [phoneNumber]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i19.AuthTokensModel>> verifyOtp(
    String? phoneNumber,
    String? pinCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [phoneNumber, pinCode]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, _i19.AuthTokensModel>
                >.value(
                  _FakeEither_2<_i18.Failure, _i19.AuthTokensModel>(
                    this,
                    Invocation.method(#verifyOtp, [phoneNumber, pinCode]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i19.AuthTokensModel>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i19.AuthTokensModel>> refreshToken(
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [refreshToken]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, _i19.AuthTokensModel>
                >.value(
                  _FakeEither_2<_i18.Failure, _i19.AuthTokensModel>(
                    this,
                    Invocation.method(#refreshToken, [refreshToken]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i19.AuthTokensModel>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>> appStart(
    String? accessToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#appStart, [accessToken]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>>.value(
                  _FakeEither_2<_i18.Failure, _i5.AppBootstrap>(
                    this,
                    Invocation.method(#appStart, [accessToken]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>>);
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i20.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i21.HomeBootstrapModel>>
  fetchHomeBootstrap() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHomeBootstrap, []),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, _i21.HomeBootstrapModel>
                >.value(
                  _FakeEither_2<_i18.Failure, _i21.HomeBootstrapModel>(
                    this,
                    Invocation.method(#fetchHomeBootstrap, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i21.HomeBootstrapModel>>);
}

/// A class which mocks [NotificationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationLocalDataSource extends _i1.Mock
    implements _i22.NotificationLocalDataSource {
  MockNotificationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i23.NotificationModel>> getNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, []),
            returnValue: _i14.Future<List<_i23.NotificationModel>>.value(
              <_i23.NotificationModel>[],
            ),
          )
          as _i14.Future<List<_i23.NotificationModel>>);

  @override
  _i14.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i14.Future<int>.value(0),
          )
          as _i14.Future<int>);

  @override
  _i14.Future<void> markAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [AddressLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressLocalDataSource extends _i1.Mock
    implements _i24.AddressLocalDataSource {
  MockAddressLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i25.AddressModel>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue: _i14.Future<List<_i25.AddressModel>>.value(
              <_i25.AddressModel>[],
            ),
          )
          as _i14.Future<List<_i25.AddressModel>>);

  @override
  _i14.Future<_i25.AddressModel?> getSelectedAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedAddress, []),
            returnValue: _i14.Future<_i25.AddressModel?>.value(),
          )
          as _i14.Future<_i25.AddressModel?>);

  @override
  _i14.Future<void> selectAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#selectAddress, [addressId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i26.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i4.UserModel> updateUser(_i27.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i14.Future<_i4.UserModel>.value(
              _FakeUserModel_3(this, Invocation.method(#updateUser, [user])),
            ),
          )
          as _i14.Future<_i4.UserModel>);
}

/// A class which mocks [ThemeModeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeModeLocalDataSource extends _i1.Mock
    implements _i28.ThemeModeLocalDataSource {
  MockThemeModeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Unit> saveThemeMode(_i29.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [mode]),
            returnValue: _i14.Future<_i3.Unit>.value(
              _FakeUnit_4(this, Invocation.method(#saveThemeMode, [mode])),
            ),
          )
          as _i14.Future<_i3.Unit>);

  @override
  _i14.Future<_i29.ThemeMode?> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i14.Future<_i29.ThemeMode?>.value(),
          )
          as _i14.Future<_i29.ThemeMode?>);
}

/// A class which mocks [LocaleLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleLocalDataSource extends _i1.Mock
    implements _i30.LocaleLocalDataSource {
  MockLocaleLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Unit> saveLocale(_i31.Locale? locale) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocale, [locale]),
            returnValue: _i14.Future<_i3.Unit>.value(
              _FakeUnit_4(this, Invocation.method(#saveLocale, [locale])),
            ),
          )
          as _i14.Future<_i3.Unit>);

  @override
  _i14.Future<_i31.Locale?> getLocale() =>
      (super.noSuchMethod(
            Invocation.method(#getLocale, []),
            returnValue: _i14.Future<_i31.Locale?>.value(),
          )
          as _i14.Future<_i31.Locale?>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> requestOtp(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [phoneNumber]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#requestOtp, [phoneNumber]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>> verifyOtp(
    String? phoneNumber,
    String? pinCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [phoneNumber, pinCode]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>>.value(
                  _FakeEither_2<_i18.Failure, _i32.AuthTokens>(
                    this,
                    Invocation.method(#verifyOtp, [phoneNumber, pinCode]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>>.value(
                  _FakeEither_2<_i18.Failure, _i32.AuthTokens>(
                    this,
                    Invocation.method(#refreshToken, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i33.AuthSession>> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i33.AuthSession>>.value(
                  _FakeEither_2<_i18.Failure, _i33.AuthSession>(
                    this,
                    Invocation.method(#checkAuthStatus, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i33.AuthSession>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>> getAppBootstrap(
    String? accessToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppBootstrap, [accessToken]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>>.value(
                  _FakeEither_2<_i18.Failure, _i5.AppBootstrap>(
                    this,
                    Invocation.method(#getAppBootstrap, [accessToken]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i34.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i66.HomeBootstrap>> fetchHomeBootstrap() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHomeBootstrap, []),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i66.HomeBootstrap>>.value(
              _FakeEither_2<_i18.Failure, _i66.HomeBootstrap>(
                this,
                Invocation.method(#fetchHomeBootstrap, []),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i66.HomeBootstrap>>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i7.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i35.Notification>> getNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, []),
            returnValue: _i14.Future<List<_i35.Notification>>.value(
              <_i35.Notification>[],
            ),
          )
          as _i14.Future<List<_i35.Notification>>);

  @override
  _i14.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i14.Future<int>.value(0),
          )
          as _i14.Future<int>);

  @override
  _i14.Future<void> markAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [AddressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRepository extends _i1.Mock implements _i8.AddressRepository {
  MockAddressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i36.Address>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue: _i14.Future<List<_i36.Address>>.value(
              <_i36.Address>[],
            ),
          )
          as _i14.Future<List<_i36.Address>>);

  @override
  _i14.Future<_i36.Address?> getSelectedAddress() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedAddress, []),
            returnValue: _i14.Future<_i36.Address?>.value(),
          )
          as _i14.Future<_i36.Address?>);

  @override
  _i14.Future<void> selectAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#selectAddress, [addressId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i9.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i27.User>> updateUser(
    _i27.User? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i27.User>>.value(
              _FakeEither_2<_i18.Failure, _i27.User>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i27.User>>);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i37.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i38.CartItem>>> getCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItems, []),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i38.CartItem>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i38.CartItem>>(
                    this,
                    Invocation.method(#getCartItems, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i38.CartItem>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, void>> addCartItem(
    _i38.CartItem? item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCartItem, [item]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, void>>.value(
              _FakeEither_2<_i18.Failure, void>(
                this,
                Invocation.method(#addCartItem, [item]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, void>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, void>> updateCartItem(
    _i38.CartItem? item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartItem, [item]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, void>>.value(
              _FakeEither_2<_i18.Failure, void>(
                this,
                Invocation.method(#updateCartItem, [item]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, void>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, void>> deleteCartItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartItem, [id]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, void>>.value(
              _FakeEither_2<_i18.Failure, void>(
                this,
                Invocation.method(#deleteCartItem, [id]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, void>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, void>> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, void>>.value(
              _FakeEither_2<_i18.Failure, void>(
                this,
                Invocation.method(#clearCart, []),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, void>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i38.CartItem?>> getCartItemById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCartItemById, [id]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i38.CartItem?>>.value(
                  _FakeEither_2<_i18.Failure, _i38.CartItem?>(
                    this,
                    Invocation.method(#getCartItemById, [id]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i38.CartItem?>>);
}

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i10.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>> getItemsBySupplierId(
    int? supplierId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsBySupplierId, [supplierId]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>>.value(
                  _FakeEither_2<_i18.Failure, List<_i39.Item>>(
                    this,
                    Invocation.method(#getItemsBySupplierId, [supplierId]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i39.Item>> getItemById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getItemById, [id]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i39.Item>>.value(
              _FakeEither_2<_i18.Failure, _i39.Item>(
                this,
                Invocation.method(#getItemById, [id]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i39.Item>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>>
  getFeaturedItemsBySupplierId(int? supplierId) =>
      (super.noSuchMethod(
            Invocation.method(#getFeaturedItemsBySupplierId, [supplierId]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>>.value(
                  _FakeEither_2<_i18.Failure, List<_i39.Item>>(
                    this,
                    Invocation.method(#getFeaturedItemsBySupplierId, [
                      supplierId,
                    ]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i40.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>> getOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>>.value(
                  _FakeEither_2<_i18.Failure, List<_i41.Order>>(
                    this,
                    Invocation.method(#getOrders, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>> getActiveOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveOrders, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>>.value(
                  _FakeEither_2<_i18.Failure, List<_i41.Order>>(
                    this,
                    Invocation.method(#getActiveOrders, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>> getPastOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getPastOrders, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>>.value(
                  _FakeEither_2<_i18.Failure, List<_i41.Order>>(
                    this,
                    Invocation.method(#getPastOrders, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i41.Order>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i41.Order>> getOrderById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [id]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i41.Order>>.value(
                  _FakeEither_2<_i18.Failure, _i41.Order>(
                    this,
                    Invocation.method(#getOrderById, [id]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i41.Order>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i41.Order>> createOrder({
    required List<_i38.CartItem>? cartItems,
    required String? deliveryAddress,
    required _i41.PaymentMethod? paymentMethod,
    required double? subtotal,
    required double? deliveryFee,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #cartItems: cartItems,
              #deliveryAddress: deliveryAddress,
              #paymentMethod: paymentMethod,
              #subtotal: subtotal,
              #deliveryFee: deliveryFee,
              #notes: notes,
            }),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i41.Order>>.value(
                  _FakeEither_2<_i18.Failure, _i41.Order>(
                    this,
                    Invocation.method(#createOrder, [], {
                      #cartItems: cartItems,
                      #deliveryAddress: deliveryAddress,
                      #paymentMethod: paymentMethod,
                      #subtotal: subtotal,
                      #deliveryFee: deliveryFee,
                      #notes: notes,
                    }),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i41.Order>>);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i11.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i42.SearchItem>>> searchItems(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchItems, [query]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i42.SearchItem>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i42.SearchItem>>(
                    this,
                    Invocation.method(#searchItems, [query]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i42.SearchItem>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i43.SearchSupplier>>>
  searchSuppliers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchSuppliers, [query]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i43.SearchSupplier>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i43.SearchSupplier>>(
                    this,
                    Invocation.method(#searchSuppliers, [query]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i43.SearchSupplier>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<String>>> getSearchSuggestions(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchSuggestions, [query]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<String>>>.value(
                  _FakeEither_2<_i18.Failure, List<String>>(
                    this,
                    Invocation.method(#getSearchSuggestions, [query]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<String>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, void>> saveSearchHistory(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSearchHistory, [query]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, void>>.value(
              _FakeEither_2<_i18.Failure, void>(
                this,
                Invocation.method(#saveSearchHistory, [query]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, void>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<String>>> getSearchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getSearchHistory, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<String>>>.value(
                  _FakeEither_2<_i18.Failure, List<String>>(
                    this,
                    Invocation.method(#getSearchHistory, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<String>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, void>> clearSearchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearSearchHistory, []),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, void>>.value(
              _FakeEither_2<_i18.Failure, void>(
                this,
                Invocation.method(#clearSearchHistory, []),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, void>>);
}

/// A class which mocks [SupplierRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplierRepository extends _i1.Mock
    implements _i12.SupplierRepository {
  MockSupplierRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i44.Supplier>>>
  getSuppliersByBusinessType(_i45.SupplierBusinessType? businessType) =>
      (super.noSuchMethod(
            Invocation.method(#getSuppliersByBusinessType, [businessType]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i44.Supplier>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i44.Supplier>>(
                    this,
                    Invocation.method(#getSuppliersByBusinessType, [
                      businessType,
                    ]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i44.Supplier>>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i44.Supplier>> getSupplierById(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSupplierById, [id]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i44.Supplier>>.value(
                  _FakeEither_2<_i18.Failure, _i44.Supplier>(
                    this,
                    Invocation.method(#getSupplierById, [id]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i44.Supplier>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i44.Supplier>>>
  getAllSuppliers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSuppliers, []),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i44.Supplier>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i44.Supplier>>(
                    this,
                    Invocation.method(#getAllSuppliers, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i44.Supplier>>>);
}

/// A class which mocks [ThemeModeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeModeRepository extends _i1.Mock
    implements _i46.ThemeModeRepository {
  MockThemeModeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> saveThemeMode(
    _i29.ThemeMode? mode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [mode]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#saveThemeMode, [mode]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i29.ThemeMode>> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i29.ThemeMode>>.value(
                  _FakeEither_2<_i18.Failure, _i29.ThemeMode>(
                    this,
                    Invocation.method(#getThemeMode, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i29.ThemeMode>>);
}

/// A class which mocks [LocaleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleRepository extends _i1.Mock implements _i47.LocaleRepository {
  MockLocaleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> saveLocale(
    _i31.Locale? locale,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocale, [locale]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#saveLocale, [locale]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i31.Locale>> getLocale() =>
      (super.noSuchMethod(
            Invocation.method(#getLocale, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i31.Locale>>.value(
                  _FakeEither_2<_i18.Failure, _i31.Locale>(
                    this,
                    Invocation.method(#getLocale, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i31.Locale>>);
}

/// A class which mocks [GetHomeBootstrapUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHomeBootstrapUseCase extends _i1.Mock
    implements _i48.GetHomeBootstrapUseCase {
  MockGetHomeBootstrapUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i66.HomeBootstrap>> call(
    _i67.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i66.HomeBootstrap>>.value(
              _FakeEither_2<_i18.Failure, _i66.HomeBootstrap>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i66.HomeBootstrap>>);
}

/// A class which mocks [RequestOtp].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestOtp extends _i1.Mock implements _i49.RequestOtp {
  MockRequestOtp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> call(
    _i49.RequestOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);
}

/// A class which mocks [VerifyOtp].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtp extends _i1.Mock implements _i50.VerifyOtp {
  MockVerifyOtp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>> call(
    _i50.VerifyOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>>.value(
                  _FakeEither_2<_i18.Failure, _i32.AuthTokens>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i32.AuthTokens>>);
}

/// A class which mocks [GetAppBootstrap].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppBootstrap extends _i1.Mock implements _i51.GetAppBootstrap {
  MockGetAppBootstrap() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>> call(
    _i51.GetAppBootstrapParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>>.value(
                  _FakeEither_2<_i18.Failure, _i5.AppBootstrap>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i5.AppBootstrap>>);
}

/// A class which mocks [CheckAuthStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAuthStatusUseCase extends _i1.Mock
    implements _i52.CheckAuthStatusUseCase {
  MockCheckAuthStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i33.AuthSession?>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, _i33.AuthSession?>>.value(
                  _FakeEither_2<_i18.Failure, _i33.AuthSession?>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i33.AuthSession?>>);
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i53.SignOutUseCase {
  MockSignOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>.value(
              _FakeEither_2<_i18.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i3.Unit>>);
}

/// A class which mocks [GetNotifications].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotifications extends _i1.Mock implements _i54.GetNotifications {
  MockGetNotifications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.NotificationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotificationRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.NotificationRepository);

  @override
  _i14.Future<List<_i35.Notification>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i14.Future<List<_i35.Notification>>.value(
              <_i35.Notification>[],
            ),
          )
          as _i14.Future<List<_i35.Notification>>);
}

/// A class which mocks [GetUnreadCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUnreadCount extends _i1.Mock implements _i55.GetUnreadCount {
  MockGetUnreadCount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.NotificationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotificationRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.NotificationRepository);

  @override
  _i14.Future<int> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i14.Future<int>.value(0),
          )
          as _i14.Future<int>);
}

/// A class which mocks [MarkAsRead].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkAsRead extends _i1.Mock implements _i56.MarkAsRead {
  MockMarkAsRead() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.NotificationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotificationRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.NotificationRepository);

  @override
  _i14.Future<void> call(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [notificationId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [MarkAllAsRead].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkAllAsRead extends _i1.Mock implements _i57.MarkAllAsRead {
  MockMarkAllAsRead() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.NotificationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotificationRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i7.NotificationRepository);

  @override
  _i14.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [GetAddresses].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAddresses extends _i1.Mock implements _i58.GetAddresses {
  MockGetAddresses() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.AddressRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAddressRepository_8(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.AddressRepository);

  @override
  _i14.Future<List<_i36.Address>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i14.Future<List<_i36.Address>>.value(
              <_i36.Address>[],
            ),
          )
          as _i14.Future<List<_i36.Address>>);
}

/// A class which mocks [GetSelectedAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSelectedAddress extends _i1.Mock
    implements _i59.GetSelectedAddress {
  MockGetSelectedAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.AddressRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAddressRepository_8(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.AddressRepository);

  @override
  _i14.Future<_i36.Address?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i14.Future<_i36.Address?>.value(),
          )
          as _i14.Future<_i36.Address?>);
}

/// A class which mocks [SelectAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectAddress extends _i1.Mock implements _i60.SelectAddress {
  MockSelectAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.AddressRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAddressRepository_8(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.AddressRepository);

  @override
  _i14.Future<void> call(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [addressId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [UpdateUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUser extends _i1.Mock implements _i61.UpdateUser {
  MockUpdateUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_9(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.UserRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, _i27.User>> call(
    _i61.UpdateUserParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i14.Future<_i3.Either<_i18.Failure, _i27.User>>.value(
              _FakeEither_2<_i18.Failure, _i27.User>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, _i27.User>>);
}

/// A class which mocks [GetItemsBySupplierId].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetItemsBySupplierId extends _i1.Mock
    implements _i62.GetItemsBySupplierId {
  MockGetItemsBySupplierId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.ItemRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeItemRepository_10(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i10.ItemRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>> call(
    _i62.GetItemsBySupplierIdParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>>.value(
                  _FakeEither_2<_i18.Failure, List<_i39.Item>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i39.Item>>>);
}

/// A class which mocks [SearchItems].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchItems extends _i1.Mock implements _i63.SearchItems {
  MockSearchItems() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.SearchRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSearchRepository_11(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i11.SearchRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i42.SearchItem>>> call(
    _i63.SearchItemsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i42.SearchItem>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i42.SearchItem>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i42.SearchItem>>>);
}

/// A class which mocks [SearchSuppliers].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchSuppliers extends _i1.Mock implements _i64.SearchSuppliers {
  MockSearchSuppliers() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.SearchRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSearchRepository_11(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i11.SearchRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i43.SearchSupplier>>> call(
    _i64.SearchSuppliersParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i43.SearchSupplier>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i43.SearchSupplier>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i43.SearchSupplier>>>);
}

/// A class which mocks [GetSuppliersByBusinessType].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSuppliersByBusinessType extends _i1.Mock
    implements _i65.GetSuppliersByBusinessType {
  MockGetSuppliersByBusinessType() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.SupplierRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSupplierRepository_12(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.SupplierRepository);

  @override
  _i14.Future<_i3.Either<_i18.Failure, List<_i44.Supplier>>> call(
    _i65.GetSuppliersByBusinessTypeParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i14.Future<
                  _i3.Either<_i18.Failure, List<_i44.Supplier>>
                >.value(
                  _FakeEither_2<_i18.Failure, List<_i44.Supplier>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i14.Future<_i3.Either<_i18.Failure, List<_i44.Supplier>>>);
}
